
name: 'deduplicate'
version: '1.0.0'


profile: 'deduplicate'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"


models:
  deduplicate:
    tests:
      orders_null_main:
        enabled: false
      customers_new_column_main:
        enabled: false
